In [1]:
import MetaTrader5 as mt5  # pip install MetaTrader5
import pandas as pd  # pip install pandas
import plotly.express as px  # pip install plotly
from datetime import datetime, timedelta
from mt5_config import login_number, path

In [2]:
result = mt5.initialize(path)
if login_number == mt5.account_info().login and result is True:
    print('Connection with MT5 established')
else:
    print('Connection failed')
    mt5.shutdown()

Connection with MT5 established

In [3]:
result = mt5.initialize()
result

True

In [4]:
symbol = 'EURCHF'
timeframe = mt5.TIMEFRAME_D1

start_dt = datetime.now() - timedelta(days=365)
end_dt = datetime.now()

In [5]:
rates = mt5.copy_rates_range(symbol, timeframe, start_dt, end_dt)
print(rates)

ohlc_df = pd.DataFrame(rates)

fig = px.line(ohlc_df, x='time', y='open')
fig.show()

ohlc_df

[(1732579200, 0.92958, 0.93268, 0.92699, 0.92987,  79355, 0, 0)
 (1732665600, 0.92957, 0.93237, 0.92772, 0.93187,  72281, 0, 0)
 (1732752000, 0.9283 , 0.933  , 0.9283 , 0.93171,  42740, 0, 0)
 (1732838400, 0.93131, 0.93259, 0.92927, 0.93154,  74783, 0, 0)
 (1733097600, 0.92811, 0.93243, 0.9281 , 0.93058,  74926, 0, 0)
 (1733184000, 0.92924, 0.9325 , 0.92862, 0.93153,  57529, 0, 0)
 (1733270400, 0.9314 , 0.93266, 0.92912, 0.92952,  65159, 0, 0)
 (1733356800, 0.9276 , 0.93225, 0.92733, 0.93011,  53359, 0, 0)
 (1733443200, 0.92953, 0.93028, 0.92415, 0.92859,  54835, 0, 0)
 (1733702400, 0.92691, 0.93025, 0.92691, 0.92739,  49360, 0, 0)
 (1733788800, 0.92707, 0.92964, 0.92559, 0.92949,  49004, 0, 0)
 (1733875200, 0.92811, 0.93036, 0.92524, 0.92797,  58490, 0, 0)
 (1733961600, 0.92594, 0.93442, 0.92547, 0.93388,  68571, 0, 0)
 (1734048000, 0.93233, 0.93867, 0.93221, 0.93778,  51661, 0, 0)
 (1734307200, 0.935  , 0.94043, 0.935  , 0.94022,  53299, 0, 0)
 (1734393600, 0.93951, 0.9418 , 0.93557, 0.9366 ,  53187, 0, 0)
 (1734480000, 0.93448, 0.93884, 0.93226, 0.93262,  67922, 0, 0)
 (1734566400, 0.93118, 0.93552, 0.93066, 0.93142,  80350, 0, 0)
 (1734652800, 0.92943, 0.93196, 0.92863, 0.93114,  66614, 0, 0)
 (1734912000, 0.92875, 0.93621, 0.92862, 0.93501,  45935, 0, 0)
 (1734998400, 0.93094, 0.9367 , 0.93094, 0.93603,  28897, 0, 0)
 (1735171200, 0.93399, 0.93814, 0.93346, 0.93663,  31236, 0, 0)
 (1735257600, 0.93478, 0.94097, 0.93396, 0.9399 ,  38283, 0, 0)
 (1735516800, 0.93806, 0.94412, 0.93805, 0.94043,  46943, 0, 0)
 (1735603200, 0.9404 , 0.94282, 0.93787, 0.93955,  43964, 0, 0)
 (1735776000, 0.93744, 0.9397 , 0.933  , 0.93661,  60233, 0, 0)
 (1735862400, 0.93573, 0.93721, 0.93326, 0.93647,  42090, 0, 0)
 (1736121600, 0.93324, 0.94097, 0.93324, 0.93982,  68331, 0, 0)
 (1736208000, 0.93973, 0.94402, 0.9373 , 0.94057,  58767, 0, 0)
 (1736294400, 0.93875, 0.94195, 0.93719, 0.94028,  60380, 0, 0)
 (1736380800, 0.93943, 0.94026, 0.93832, 0.93951,  43877, 0, 0)
 (1736467200, 0.93912, 0.94192, 0.93687, 0.93882,  60764, 0, 0)
 (1736726400, 0.93699, 0.93954, 0.93372, 0.9393 ,  57624, 0, 0)
 (1736812800, 0.93849, 0.94162, 0.93689, 0.94033,  57066, 0, 0)
 (1736899200, 0.93912, 0.94127, 0.93752, 0.93912,  53179, 0, 0)
 (1736985600, 0.93698, 0.93938, 0.93698, 0.93816,  56436, 0, 0)
 (1737072000, 0.9362 , 0.94143, 0.9362 , 0.9395 ,  53315, 0, 0)
 (1737331200, 0.93854, 0.94601, 0.93826, 0.94437,  60910, 0, 0)
 (1737417600, 0.94208, 0.94575, 0.94122, 0.94404,  69637, 0, 0)
 (1737504000, 0.94368, 0.94548, 0.94288, 0.94369,  47596, 0, 0)
 (1737590400, 0.94253, 0.94584, 0.94185, 0.94492,  82414, 0, 0)
 (1737676800, 0.94454, 0.95176, 0.94278, 0.95069,  65853, 2, 0)
 (1737936000, 0.94931, 0.95011, 0.94271, 0.94626,  73884, 2, 0)
 (1738022400, 0.94534, 0.94611, 0.94289, 0.94297,  66249, 2, 0)
 (1738108800, 0.94277, 0.94608, 0.9417 , 0.94481,  67195, 2, 0)
 (1738195200, 0.94442, 0.9485 , 0.94296, 0.9453 ,  71472, 2, 0)
 (1738281600, 0.94459, 0.94681, 0.94272, 0.94379,  84358, 2, 0)
 (1738540800, 0.93688, 0.94195, 0.93597, 0.94147, 121293, 2, 0)
 (1738627200, 0.93999, 0.94192, 0.9376 , 0.93928,  65191, 2, 0)
 (1738713600, 0.93903, 0.94066, 0.93586, 0.93792,  61347, 2, 0)
 (1738800000, 0.93686, 0.94033, 0.93672, 0.93952,  56451, 2, 0)
 (1738886400, 0.93732, 0.94293, 0.93714, 0.93944,  72289, 2, 0)
 (1739145600, 0.93645, 0.94053, 0.93485, 0.93926,  49336, 2, 0)
 (1739232000, 0.93807, 0.94707, 0.93759, 0.94619,  46928, 2, 0)
 (1739318400, 0.94575, 0.95075, 0.94271, 0.94851,  69189, 2, 0)
 (1739404800, 0.94645, 0.95132, 0.9401 , 0.94505,  80137, 2, 0)
 (1739491200, 0.94432, 0.94726, 0.94251, 0.94386,  58227, 2, 0)
 (1739750400, 0.94063, 0.94503, 0.94063, 0.94419,  42110, 2, 0)
 (1739836800, 0.94242, 0.94461, 0.94149, 0.94354,  48182, 2, 0)
 (1739923200, 0.9412 , 0.94548, 0.94062, 0.94272,  53012, 2, 0)
 (1740009600, 0.94214, 0.94348, 0.9405 , 0.94277,  51091, 2, 0)
 (1740096000, 0.94227, 0.9435 , 0.93802, 0.93893,  56512, 2, 0)
 (1740355200, 0.93898, 0.94279, 0.93749, 0.93905,  63818, 2, 0)
 (1740441600, 0.93859, 0.93996, 0.93662, 0.93882,  55978, 2, 0)
 (1740528000, 0.93686, 0.94003, 0.93686, 0.93794,  58951, 2, 0)
 (1740614400, 0.93654, 0.94159, 0.93503, 0.93541,  62346, 2, 0)
 (1740700800, 0.9354 , 0.9404 , 0.93295, 0.9368 ,  69068, 2, 0)
 (1740960000, 0.93704, 0.94354, 0.93656, 0.94048,  79080, 2, 0)
 (1741046400, 0.94035, 0.94522, 0.93455, 0.945  , 104682, 2, 0)
 (1741132800, 0.94299, 0.96232, 0.94248, 0.96099, 115844, 2, 0)
 (1741219200, 0.95958, 0.96358, 0.95146, 0.95268, 119403, 2, 0)
 (1741305600, 0.95238, 0.95741, 0.95137, 0.95285, 110165, 2, 0)
 (1741564800, 0.95138, 0.95565, 0.94905, 0.95442,  99397, 2, 0)
 (1741651200, 0.95403, 0.96496, 0.95195, 0.96365, 108262, 2, 0)
 (1741737600, 0.9636 , 0.96497, 0.95989, 0.95992,  79708, 2, 0)
 (1741824000, 0.95915, 0.96218, 0.95637, 0.95709,  81660, 2, 0)
 (1741910400, 0.95657, 0.96621, 0.95548, 0.96288,  76280, 2, 0)
 (1742169600, 0.96096, 0.96322, 0.96073, 0.96193,  62739, 2, 0)
 (1742256000, 0.96176, 0.96373, 0.9577 , 0.95946,  59981, 2, 0)
 (1742342400, 0.95867, 0.95983, 0.95414, 0.9565 ,  66765, 2, 0)
 (1742428800, 0.95641, 0.9583 , 0.95299, 0.95695,  74129, 2, 0)
 (1742515200, 0.95614, 0.95788, 0.95399, 0.95496,  61961, 2, 0)
 (1742774400, 0.95374, 0.95772, 0.95288, 0.95347,  63847, 2, 0)
 (1742860800, 0.95218, 0.95538, 0.95125, 0.95236,  56023, 2, 0)
 (1742947200, 0.95208, 0.95462, 0.94918, 0.95022,  57419, 0, 0)
 (1743033600, 0.95013, 0.9542 , 0.949  , 0.95232,  60736, 0, 0)
 (1743120000, 0.95198, 0.95499, 0.95032, 0.95383,  52010, 0, 0)
 (1743379200, 0.95175, 0.95727, 0.95175, 0.95632,  64344, 0, 0)
 (1743465600, 0.95618, 0.95686, 0.95123, 0.9536 ,  60111, 0, 0)
 (1743552000, 0.95367, 0.96324, 0.95117, 0.95738,  61126, 0, 0)
 (1743638400, 0.95661, 0.95782, 0.94676, 0.94953, 139839, 0, 0)
 (1743724800, 0.94952, 0.94964, 0.93632, 0.94302, 163913, 0, 0)
 (1743984000, 0.92986, 0.95005, 0.92913, 0.93833, 206630, 0, 0)
 (1744070400, 0.9357 , 0.941  , 0.92783, 0.92866, 139908, 0, 0)
 (1744156800, 0.92883, 0.93934, 0.92536, 0.93885, 182513, 0, 0)
 (1744243200, 0.93729, 0.94091, 0.9224 , 0.9227 , 170617, 0, 0)
 (1744329600, 0.92248, 0.93207, 0.92134, 0.92522, 186987, 0, 0)
 (1744588800, 0.9249 , 0.93535, 0.92328, 0.92479, 124979, 0, 0)
 (1744675200, 0.92417, 0.92961, 0.92296, 0.92878,  86315, 0, 0)
 (1744761600, 0.92747, 0.93001, 0.92388, 0.92701, 107587, 0, 0)
 (1744848000, 0.92663, 0.93384, 0.92548, 0.93112,  87942, 0, 0)
 (1744934400, 0.93027, 0.93206, 0.92934, 0.92944, 308531, 0, 0)
 (1745193600, 0.92902, 0.93223, 0.92754, 0.93117,  98792, 0, 0)
 (1745280000, 0.93128, 0.93621, 0.92796, 0.93528, 102402, 0, 0)
 (1745366400, 0.93516, 0.94105, 0.93306, 0.93952, 115371, 0, 0)
 (1745452800, 0.93842, 0.94263, 0.93788, 0.94158,  81124, 0, 0)
 (1745539200, 0.94039, 0.94466, 0.93985, 0.94052,  76128, 0, 0)
 (1745798400, 0.94078, 0.94371, 0.93617, 0.9364 ,  75272, 0, 0)
 (1745884800, 0.93633, 0.94068, 0.93605, 0.93794,  69200, 0, 0)
 (1745971200, 0.93731, 0.93945, 0.93299, 0.93614,  80382, 0, 0)
 (1746057600, 0.93444, 0.93953, 0.9335 , 0.93636,  67215, 0, 0)
 (1746144000, 0.93609, 0.93835, 0.93114, 0.93371,  79740, 0, 0)
 (1746403200, 0.93275, 0.93702, 0.93003, 0.93019,  64836, 0, 0)
 (1746489600, 0.93011, 0.93592, 0.92936, 0.93427,  65825, 0, 0)
 (1746576000, 0.9342 , 0.9388 , 0.93014, 0.93068,  75648, 0, 0)
 (1746662400, 0.93012, 0.93477, 0.93012, 0.9337 ,  72502, 0, 0)
 (1746748800, 0.93253, 0.93606, 0.93134, 0.93539,  60359, 0, 0)
 (1747008000, 0.93279, 0.93943, 0.93226, 0.93738,  88387, 0, 0)
 (1747094400, 0.93742, 0.9409 , 0.93307, 0.93887,  64529, 0, 0)
 (1747180800, 0.93853, 0.94212, 0.93744, 0.94092,  70995, 0, 0)
 (1747267200, 0.94071, 0.94116, 0.93396, 0.93455,  63071, 0, 0)
 (1747353600, 0.93475, 0.93825, 0.93338, 0.93465,  52932, 0, 0)
 (1747612800, 0.93308, 0.93965, 0.93257, 0.93817,  73685, 0, 0)
 (1747699200, 0.93631, 0.93855, 0.93461, 0.93462,  64806, 0, 0)
 (1747785600, 0.93448, 0.93638, 0.93136, 0.935  ,  82540, 0, 0)
 (1747872000, 0.93465, 0.93554, 0.93302, 0.93481,  73579, 0, 0)
 (1747958400, 0.93491, 0.93807, 0.92931, 0.93332,  70705, 0, 0)
 (1748217600, 0.93163, 0.93675, 0.93151, 0.93468,  47961, 0, 0)
 (1748304000, 0.93318, 0.9391 , 0.93317, 0.93711,  65107, 0, 0)
 (1748390400, 0.93656, 0.93842, 0.93355, 0.93388,  61499, 0, 0)
 (1748476800, 0.93337, 0.93722, 0.93206, 0.93517,  79379, 0, 0)
 (1748563200, 0.93248, 0.93574, 0.93088, 0.9337 ,  69709, 0, 0)
 (1748822400, 0.9337 , 0.93543, 0.93203, 0.93487,  67633, 0, 0)
 (1748908800, 0.93513, 0.93815, 0.93312, 0.93678,  59478, 0, 0)
 (1748995200, 0.93417, 0.93803, 0.93382, 0.9343 ,  65530, 0, 0)
 (1749081600, 0.93359, 0.93995, 0.93076, 0.93793,  76607, 0, 0)
 (1749168000, 0.93628, 0.93972, 0.93628, 0.93655,  64523, 0, 0)
 (1749427200, 0.93549, 0.93868, 0.93499, 0.93819,  46231, 0, 0)
 (1749513600, 0.93749, 0.94039, 0.93636, 0.93985,  61787, 0, 0)
 (1749600000, 0.93907, 0.94292, 0.93722, 0.94196,  60326, 0, 0)
 (1749686400, 0.94016, 0.94278, 0.93865, 0.93866,  74787, 0, 0)
 (1749772800, 0.93688, 0.93917, 0.93076, 0.93676,  92223, 0, 0)
 (1750032000, 0.93379, 0.94192, 0.93281, 0.94053,  79121, 2, 0)
 (1750118400, 0.93985, 0.94185, 0.93599, 0.93705,  70726, 2, 0)
 (1750204800, 0.93334, 0.94224, 0.93156, 0.93981,  77650, 2, 0)
 (1750291200, 0.93899, 0.94188, 0.93611, 0.9384 ,  73690, 2, 0)
 (1750377600, 0.93646, 0.94258, 0.93628, 0.94199,  70198, 2, 0)
 (1750636800, 0.93504, 0.94105, 0.93485, 0.94085, 115355, 2, 0)
 (1750723200, 0.93965, 0.94283, 0.93393, 0.93467,  91895, 2, 0)
 (1750809600, 0.93452, 0.93843, 0.93329, 0.93818,  75261, 2, 0)
 (1750896000, 0.93682, 0.9402 , 0.93554, 0.93598,  88385, 2, 0)
 (1750982400, 0.93547, 0.9381 , 0.93312, 0.93558,  78712, 2, 0)
 (1751241600, 0.93594, 0.93734, 0.93352, 0.93483,  90403, 2, 0)
 (1751328000, 0.93444, 0.93478, 0.93062, 0.9333 ,  80997, 2, 0)
 (1751414400, 0.93281, 0.93444, 0.92996, 0.93435,  71732, 2, 0)
 (1751500800, 0.93337, 0.93645, 0.93144, 0.93498,  73818, 2, 0)
 (1751587200, 0.93238, 0.93619, 0.93226, 0.93394,  94955, 2, 0)
 (1751846400, 0.93455, 0.93587, 0.93135, 0.93431,  78205, 2, 0)
 (1751932800, 0.93273, 0.93668, 0.93219, 0.93296,  75928, 2, 0)
 (1752019200, 0.9331 , 0.93452, 0.93041, 0.93093,  72332, 2, 0)
 (1752105600, 0.9284 , 0.93278, 0.92702, 0.93232,  65613, 2, 0)
 (1752192000, 0.93201, 0.93265, 0.92955, 0.93044,  70751, 2, 0)
 (1752451200, 0.92945, 0.93213, 0.92702, 0.93064,  72019, 2, 0)
 (1752537600, 0.93039, 0.93117, 0.92782, 0.92985,  70806, 2, 0)
 (1752624000, 0.9293 , 0.93342, 0.92684, 0.93192,  95858, 2, 0)
 (1752710400, 0.93057, 0.93356, 0.93004, 0.93283,  72841, 2, 0)
 (1752796800, 0.93235, 0.93404, 0.93032, 0.93148,  67835, 2, 0)
 (1753056000, 0.92932, 0.93342, 0.92878, 0.9328 ,  71352, 2, 0)
 (1753142400, 0.93159, 0.9338 , 0.93058, 0.93093,  67256, 2, 0)
 (1753228800, 0.93026, 0.93433, 0.92934, 0.93283,  81062, 2, 0)
 (1753315200, 0.9312 , 0.9363 , 0.9309 , 0.93435,  75491, 2, 0)
 (1753401600, 0.93348, 0.93539, 0.931  , 0.93301,  67894, 2, 0)
 (1753660800, 0.93494, 0.93598, 0.9297 , 0.931  ,  86798, 2, 0)
 (1753747200, 0.92956, 0.93243, 0.92751, 0.93041,  83138, 2, 0)
 (1753833600, 0.92978, 0.93151, 0.92869, 0.92941,  91132, 2, 0)
 (1753920000, 0.92866, 0.93079, 0.92505, 0.92713,  80518, 2, 0)
 (1754006400, 0.92622, 0.93245, 0.92532, 0.93123, 119775, 2, 0)
 (1754265600, 0.93306, 0.93592, 0.92964, 0.93481,  96878, 2, 0)
 (1754352000, 0.9346 , 0.93603, 0.93054, 0.93445,  85782, 2, 0)
 (1754438400, 0.9332 , 0.9407 , 0.93167, 0.93976,  80469, 2, 0)
 (1754524800, 0.9394 , 0.94281, 0.93841, 0.94056,  94031, 2, 0)
 (1754611200, 0.94049, 0.94206, 0.9381 , 0.94029,  77816, 2, 0)
 (1754870400, 0.93921, 0.94376, 0.93883, 0.94363,  74364, 2, 0)
 (1754956800, 0.94113, 0.94399, 0.94009, 0.94099,  90165, 2, 0)
 (1755043200, 0.94098, 0.94291, 0.94001, 0.94256,  80221, 2, 0)
 (1755129600, 0.93978, 0.94318, 0.93885, 0.94051,  88515, 2, 0)
 (1755216000, 0.94022, 0.94425, 0.9382 , 0.94335,  72976, 2, 0)
 (1755475200, 0.94259, 0.94453, 0.941  , 0.94123,  77498, 2, 0)
 (1755561600, 0.94024, 0.94218, 0.93913, 0.94028,  70151, 2, 0)
 (1755648000, 0.94014, 0.94135, 0.93633, 0.93656,  74387, 2, 0)
 (1755734400, 0.93537, 0.93945, 0.93499, 0.93833,  78592, 2, 0)
 (1755820800, 0.93705, 0.94017, 0.93462, 0.93906,  84524, 2, 0)
 (1756080000, 0.93854, 0.94048, 0.93617, 0.93617,  67630, 2, 0)
 (1756166400, 0.93524, 0.93867, 0.9324 , 0.93504,  85618, 2, 0)
 (1756252800, 0.93487, 0.93593, 0.93182, 0.93354,  73179, 2, 0)
 (1756339200, 0.93323, 0.93672, 0.93144, 0.93575,  73988, 2, 0)
 (1756425600, 0.9348 , 0.93686, 0.93408, 0.93536,  75259, 2, 0)
 (1756684800, 0.93369, 0.93837, 0.93303, 0.9372 ,  66094, 2, 0)
 (1756771200, 0.93586, 0.93815, 0.93539, 0.93649,  93418, 2, 0)
 (1756857600, 0.93434, 0.93807, 0.93394, 0.93775,  76733, 2, 0)
 (1756944000, 0.93624, 0.93937, 0.93517, 0.93854,  80162, 2, 0)
 (1757030400, 0.93638, 0.93959, 0.93444, 0.93476,  86116, 2, 0)
 (1757289600, 0.93375, 0.93626, 0.93018, 0.93306,  84823, 2, 0)
 (1757376000, 0.93147, 0.93418, 0.9314 , 0.93353,  82768, 2, 0)
 (1757462400, 0.92846, 0.93544, 0.92846, 0.93459,  80084, 2, 0)
 (1757548800, 0.93402, 0.93544, 0.93154, 0.93385,  81356, 2, 0)
 (1757635200, 0.93317, 0.935  , 0.93167, 0.9344 ,  57426, 2, 0)
 (1757894400, 0.93431, 0.93563, 0.93275, 0.93442,  44151, 2, 0)
 (1757980800, 0.93389, 0.93499, 0.93192, 0.93232,  67034, 2, 0)
 (1758067200, 0.93168, 0.93347, 0.93056, 0.93152,  68671, 2, 0)
 (1758153600, 0.93129, 0.93433, 0.92962, 0.93385,  74697, 2, 0)
 (1758240000, 0.9324 , 0.93558, 0.9307 , 0.93423,  79580, 2, 0)
 (1758499200, 0.93257, 0.9355 , 0.93171, 0.93515,  61712, 2, 0)
 (1758585600, 0.93446, 0.93559, 0.93393, 0.93481,  67389, 2, 0)
 (1758672000, 0.9348 , 0.9353 , 0.93238, 0.93311,  65788, 2, 0)
 (1758758400, 0.93293, 0.93509, 0.93078, 0.9325 ,  66714, 2, 0)
 (1758844800, 0.93251, 0.93407, 0.93132, 0.93352,  62413, 2, 0)
 (1759104000, 0.93302, 0.93651, 0.93201, 0.93529,  60093, 2, 0)
 (1759190400, 0.93422, 0.93711, 0.9336 , 0.93417,  60725, 2, 0)
 (1759276800, 0.93303, 0.93729, 0.93234, 0.93482,  78365, 2, 0)
 (1759363200, 0.93409, 0.93637, 0.93314, 0.93475,  61620, 2, 0)
 (1759449600, 0.93424, 0.93576, 0.93245, 0.93323,  51130, 2, 0)
 (1759708800, 0.93292, 0.93471, 0.93071, 0.93079,  75606, 2, 0)
 (1759795200, 0.93039, 0.93157, 0.92996, 0.93045,  62277, 2, 0)
 (1759881600, 0.93017, 0.93266, 0.92792, 0.93231,  58906, 2, 0)
 (1759968000, 0.932  , 0.93295, 0.93008, 0.93237,  64322, 2, 0)
 (1760054400, 0.9309 , 0.93315, 0.92765, 0.92788,  67267, 2, 0)
 (1760313600, 0.93012, 0.93199, 0.92817, 0.93022,  64094, 2, 0)
 (1760400000, 0.92892, 0.93087, 0.92819, 0.92953,  67896, 2, 0)
 (1760486400, 0.92937, 0.93107, 0.9266 , 0.92794,  59219, 2, 0)
 (1760572800, 0.92764, 0.93048, 0.92611, 0.92627,  72799, 2, 0)
 (1760659200, 0.92624, 0.92681, 0.92189, 0.92418,  97959, 2, 0)
 (1760918400, 0.9228 , 0.92588, 0.92143, 0.92258,  63989, 2, 0)
 (1761004800, 0.91987, 0.92452, 0.91987, 0.9237 ,  78516, 2, 0)
 (1761091200, 0.92341, 0.92453, 0.92126, 0.92411,  70092, 2, 0)
 (1761177600, 0.92302, 0.9254 , 0.92267, 0.92373,  48715, 2, 0)
 (1761264000, 0.92349, 0.92544, 0.92261, 0.92477,  58127, 2, 0)
 (1761523200, 0.92611, 0.92707, 0.9243 , 0.9261 ,  53487, 1, 0)
 (1761609600, 0.92465, 0.92671, 0.9241 , 0.92432,  48842, 1, 0)
 (1761696000, 0.92363, 0.92891, 0.92319, 0.92808,  68577, 1, 0)
 (1761782400, 0.9275 , 0.92894, 0.92534, 0.92728,  62943, 1, 0)
 (1761868800, 0.92636, 0.9292 , 0.92586, 0.92786,  55513, 1, 0)
 (1762128000, 0.92507, 0.93115, 0.92507, 0.93074,  56544, 1, 0)
 (1762214400, 0.92922, 0.93169, 0.92899, 0.9305 ,  54750, 1, 0)
 (1762300800, 0.9282 , 0.932  , 0.9276 , 0.93117,  54454, 1, 0)
 (1762387200, 0.92954, 0.93211, 0.92882, 0.9309 ,  50521, 0, 0)
 (1762473600, 0.9299 , 0.93265, 0.9299 , 0.93066,  49819, 1, 0)
 (1762732800, 0.92971, 0.93257, 0.9293 , 0.93   ,  55259, 1, 0)
 (1762819200, 0.92961, 0.93134, 0.92612, 0.92712,  44305, 1, 0)
 (1762905600, 0.92654, 0.92747, 0.92328, 0.9247 ,  43240, 1, 0)
 (1762992000, 0.92303, 0.92585, 0.92144, 0.92224,  55802, 1, 0)
 (1763078400, 0.9212 , 0.92305, 0.91794, 0.92227,  63339, 0, 0)
 (1763337600, 0.92191, 0.92312, 0.92117, 0.92282,  46129, 1, 0)
 (1763424000, 0.92254, 0.92644, 0.92012, 0.92604,  55757, 1, 0)
 (1763510400, 0.92391, 0.92958, 0.92366, 0.92928,  63378, 1, 0)
 (1763596800, 0.92891, 0.93054, 0.92666, 0.92885,  63236, 1, 0)
 (1763683200, 0.92813, 0.93098, 0.92607, 0.93068,  66145, 1, 0)
 (1763942400, 0.92907, 0.93253, 0.9289 , 0.93124,  48572, 0, 0)
 (1764028800, 0.93104, 0.93507, 0.9303 , 0.93441,  47809, 0, 0)]

,time,open,high,low,close,tick_volume,spread,real_volume
0,1732579200,0.92958,0.93268,0.92699,0.92987,79355,0,0
1,1732665600,0.92957,0.93237,0.92772,0.93187,72281,0,0
2,1732752000,0.92830,0.93300,0.92830,0.93171,42740,0,0
3,1732838400,0.93131,0.93259,0.92927,0.93154,74783,0,0
4,1733097600,0.92811,0.93243,0.92810,0.93058,74926,0,0
...,...,...,...,...,...,...,...,...
254,1763510400,0.92391,0.92958,0.92366,0.92928,63378,1,0
255,1763596800,0.92891,0.93054,0.92666,0.92885,63236,1,0
256,1763683200,0.92813,0.93098,0.92607,0.93068,66145,1,0
257,1763942400,0.92907,0.93253,0.92890,0.93124,48572,0,0
258,1764028800,0.93104,0.93507,0.93030,0.93441,47809,0,0

In [6]:
period = 20
num_std = 1.5

ohlc_df['sma'] = ohlc_df['open'].rolling(period).mean()
ohlc_df['std'] = ohlc_df['open'].rolling(period).std()

ohlc_df['upper_band'] = ohlc_df['sma'] + num_std * ohlc_df['std']
ohlc_df['lower_band'] = ohlc_df['sma'] - num_std * ohlc_df['std']

ohlc_df

,time,open,high,low,close,tick_volume,spread,real_volume,sma,std,upper_band,lower_band
0,1732579200,0.92958,0.93268,0.92699,0.92987,79355,0,0,NaN,NaN,NaN,NaN
1,1732665600,0.92957,0.93237,0.92772,0.93187,72281,0,0,NaN,NaN,NaN,NaN
2,1732752000,0.92830,0.93300,0.92830,0.93171,42740,0,0,NaN,NaN,NaN,NaN
3,1732838400,0.93131,0.93259,0.92927,0.93154,74783,0,0,NaN,NaN,NaN,NaN
4,1733097600,0.92811,0.93243,0.92810,0.93058,74926,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
254,1763510400,0.92391,0.92958,0.92366,0.92928,63378,1,0,0.925757,0.002899,0.930105,0.921409
255,1763596800,0.92891,0.93054,0.92666,0.92885,63236,1,0,0.926052,0.002905,0.930409,0.921694
256,1763683200,0.92813,0.93098,0.92607,0.93068,66145,1,0,0.926283,0.002875,0.930596,0.921971
257,1763942400,0.92907,0.93253,0.92890,0.93124,48572,0,0,0.926431,0.002941,0.930843,0.922020
258,1764028800,0.93104,0.93507,0.93030,0.93441,47809,0,0,0.926751,0.003081,0.931373,0.922129

In [7]:
px.line(ohlc_df, x='time', y=['open', 'sma', 'upper_band', 'lower_band'])